
---
title:  "`r ifelse(input$Province=='تهران',print('Summary report for COVID19 in the World'),paste('Summary report for COVID-19 in',input$Province,ifelse(input$Province != 'تهران', paste(',',input$Province) ,'')))`"

author: | 
  | This report generated by COVID19 Reporter dashboard created by Dr.[Mahdi Hadi](https://www.tums.ac.ir/faculties/m-hadi), Ph.D. of Environmental Health Engineering, Assisstant Professor at the Institute for Environmental Research (IER), Center for Water Quality Research (CWQR), Tehran University of Medical Sciences,Tehran, Iran.
  Email:m.hadi1981@gmail.com ; m-hadi@sina.tums.ac.ir
date:  
output: html_document
 

---


::: {dir="rtl" style="font-family: Vazir;background:rgba(0, 247, 255, .85);border-radius: 15px; padding: 10px;border: 3px solid orange;position:absolute;top:0px;left:0px;width: 100%;margin:0px 0px 0px 0px;"}
#### راهنمای نحوه ثبت اطلاعات تماس فردی در این سامانه {style="color: brown"}

#### ضمن عرض تشکر از مشارکت شما هموطن عزیز لطفاً قبل از شروع به ثبت اطلاعات، این راهنما را مطالعه فرمایید: {style="color:navy"}

#### راهنمای فوری {style="color: green"}

#### راهنمای تکمیلی {style="color: navy"}

<font size="3">

-   به منظور ثبت اطلاعات تماسهای روزانه خود با سایر افراد در این سامانه ابتدا لازم است تا برای ورود به صفحه شخصی خود در سامانه ثبت نام کنید. برای این منظور ابتدا بر روی دکمه "**ثبت نام**" کلیک و در پنجره باز شده مطابق شکل زیر بعد از وارد کردن نام و نام خانوادگی در قسمت رمز عبور یک رمز عبور دلخواه وارد و در کادر بعدی مجدد آن را وارد کنید. **دقت کنید موقع وارد کردن رمز عبورصفحه کلید شما روی زبان انگلیسی باشد**. در این پنجره همچنین لازم است **شماره تلفن همراه** و **کد ملی** خود را نیز وارد نمایید. دقت نمایید شماره تلفن همراه و کد ملی شما صرفا جهت اطمینان از صحت اطلاعات و همچنین امکان اطلاع رسانی های بعدی و بازیابی رمز عبور در صورت فراموش کردن آن از طریق پیامک مورد استفاده قرار می گیرد و کاربرد دیگری ندارد. بعد از وارد کردن موارد خواسته شده، بر روی دکمه "**ارسال اطلاعات**" کلیک کنید تا شماره کاربری شما توسط سامانه به شماره تلفن همراه شما ارسال شود.

</font>
:::




```{r,echo=FALSE , warning=FALSE}
# take mean with confience interval from columns
MeanFunc<-function(x) round(mean(x,na.rm = TRUE),digits=6 )
SEFunc<-function(x) round(qt(0.975,df=sum(!is.na(x))-1)*sd(x,na.rm = TRUE)/sqrt(sum(!is.na(x)) ),digits=5 )
SDFunc<-function(x) round(sd(x,na.rm = TRUE),digits=5 )
LeftFunc<-function(x)  round(mean(x,na.rm = TRUE)-SEFunc(x),digits=5) 
RightFunc<-function(x) round(mean(x,na.rm = TRUE)+SEFunc(x),digits=5)  
MaxFunc<-function(x) round(max(x,na.rm = TRUE) ,digits=5)  
MinFunc<-function(x) round(min(x,na.rm = TRUE) ,digits=5) 

multi.fun <- function(x) {
  c(Mean = MeanFunc(x), SE = SEFunc(x), SD = SDFunc(x), Left=LeftFunc(x),Right=RightFunc(x),Max=MaxFunc(x),Min=MinFunc(x))
}

WorldSummary<-apply(LatestDataTable()[,3:8],2, multi.fun)
CountrySummary<-apply(CountryDataTable()[,7:9],2, multi.fun)

```


```{=html}
<style>
  @font-face {
    font-family: "Vazir";
    src: url("./fonts/Vazir.eot");
    src: url("./fonts/Vazir.woff") format("woff"),
    url("./fonts/Vazir.otf") format("opentype"),
    url("./fonts/Vazir.svg") format("svg");
  }
body { 
  font-family: "Vazir";
  text-align: justify;
}
</style>
```


