---
---
---

::: {dir="rtl" style="font-family: Vazir;background:rgba(0, 247, 255, .85);border-radius: 15px; padding: 10px;border: 3px solid orange;position:absolute;top:0px;left:0px;width: 100%;margin:0px 0px 0px 0px;"}
#### راهنمای نحوه ثبت اطلاعات تماس فردی در این سامانه {style="color: brown"}

#### ضمن عرض تشکر از مشارکت شما هموطن عزیز لطفاً قبل از شروع به ثبت اطلاعات، این راهنما را مطالعه فرمایید: {style="color:navy"}

#### راهنمای فوری {style="color: green"}

#### راهنمای تکمیلی {style="color: navy"}

<font size="3">

-   به منظور ثبت اطلاعات تماسهای روزانه خود با سایر افراد در این سامانه ابتدا لازم است تا برای ورود به صفحه شخصی خود در سامانه ثبت نام کنید. برای این منظور ابتدا بر روی دکمه "**ثبت نام**" کلیک و در پنجره باز شده مطابق شکل زیر بعد از وارد کردن نام و نام خانوادگی در قسمت رمز عبور یک رمز عبور دلخواه وارد و در کادر بعدی مجدد آن را وارد کنید. **دقت کنید موقع وارد کردن رمز عبورصفحه کلید شما روی زبان انگلیسی باشد**. در این پنجره همچنین لازم است **شماره تلفن همراه** و **کد ملی** خود را نیز وارد نمایید. دقت نمایید شماره تلفن همراه و کد ملی شما صرفا جهت اطمینان از صحت اطلاعات و همچنین امکان اطلاع رسانی های بعدی و بازیابی رمز عبور در صورت فراموش کردن آن از طریق پیامک مورد استفاده قرار می گیرد و کاربرد دیگری ندارد. بعد از وارد کردن موارد خواسته شده، بر روی دکمه "**ارسال اطلاعات**" کلیک کنید تا شماره کاربری شما توسط سامانه به شماره تلفن همراه شما ارسال شود.

-   بعد از ثبت رمز عبور و دریافت شماره کاربری از طریق SMS ، می توانید با وارد کردن شماره کاربری پیشنهادی و رمز عبور خود در صفحه اول سامانه و سپس کلیک کردن دکمه "**ورود**" (مطابق شکل زیر) وارد صفحه شخصی خود شوید.

-   بعد از ورود به صفحه شخصی خود، اولین فرمی که بایستی تکمیل فرمایید را مشاهده خواهید کرد. همانطور که در شکل زیر دیده میشود دراین فرم سوالاتی در مورد شخص شما که اکنون ثبت نام کرده و وارد این سامانه شده اید پرسیده می شود. این اطلاعات شامل موارد زیر می باشد:

    ::: {dir="rtl" style="color: green"}
    -   **مشخصات شما از نظر سرپرستی خانوار (والدین، نوجوان 11-18 سال، بالغ 18 سال به بالا)**
    -   **جنسیت شما**
    -   **سن شما**
    -   **تعداد اعضای خانواده شما**
    -   **وضعیت شغلی شما**
    -   **سطح تحصیلات شما**
    -   **استان محل زندگی شما**
    -   **شهر محل زندگی شما**
    -   **وضعیت ابتلا به بیماری COVID-19**
    -   **رفتارهای مراقبتی در برابر COVID-19**
    -   **تاریخ تکمیل فرم**
    :::

-   بعد از اینکه فرم فوق را تکمیل نمودید، بر روی دکمه "شروع تکمیل پرسشنامه روزانه" کلیک کنید. با کلیک بر روی این دکمه، پنجره تایید رضایت آگاهانه نمایش داده می شود و در صورت تایید موارد خواسته شده، فرم اولیه ذخیره شده و وارد صفحه بعدی (صفحه درج اطلاعات تماس) که مربوط به ثبت اطلاعات تماس روزانه می باشد ( مطابق شکل زیر) خواهید شد:

-   همانطور که در شکل فوق دیده می شود با زدن بر روی دکمه "افزودن" می توانید موارد تماسهای روزانه را برای خود یا برای هر یک ازاعضای خانواده خود ثبت کنید. با زدن دکمه "افزودن" پنجره ای باز می شود مطابق شکل زیر که در قسمت بالای آن ابتدا عضوی از خانواده که قصد دارید تماسهای وی را ثبت کنید انتخاب می کنید و جنسیت و سن وی را وارد می کنید. مثلا اگر فردی قصد داشته باشد تماسهایی را که در تاریخ 17 فروردین داشته است برای "خودش" ثبت کند باید اول "خودم" را انتخاب کند و سپس جنسیت و سن خود را مانند شکل زیر وارد نماید:

-   توجه بفرمایید در فرم درج اطلاعات تماس، شما می توانید اطلاعات [**تماس**]{.ul} خود با [**تمام افرادی**]{.ul} که در [**یک روز مشخص**]{.ul} داشته اید را ثبت کنید. به عنوان مثال فرض کنید شما ساعت 6 صبح از خانه خارج شدید و در جلوی درب منزل به مدت پنج دقیقه با همسایه خود گپ و گفت کردید سپس به نانوایی رفتید و در آنجا به مدت 2 دقیقه با یکی از دوستان سلام و احوالپرسی کردید. از آنجا به فروشگاه رفته و در آنجا یکی از دوستان خود را می بینید و به مدت 10 دقیقه نیز با او گفتگو می کنید. بعد به خانه می آیید و در خانه به مدت یک ساعت با فرزند خردسال خود بازی می کنید. در این مثال شما با چهار نفر تماس داشتید که می توانید تمامی تماسهایی که در این روز داشته اید را در سامانه ثبت کنید. با توجه به اینکه ممکن است شما در روزهای کاری تماسهای بیشتری داشته باشید لطفا اطلاعات تماسهای خود را برای **یک روز کاری (مثلا یکی از روزها از شنبه تا چهارشنبه)** و همچنین برای **یک روز تعطیل (جمعه یا سایر تعطیلات رسمی)** ثبت کنید.

-   همانطور که در مثالهای بالا نیز گفته شد منظور ما از [**تماس**]{.ul} شما با سایر افراد هر یک از موارد زیر است و [**تماس هایی که از طریق تلفن انجام می شوند مد نظر نمی باشند**]{.ul}:\

    ::: {dir="rtl" style="color: red"}
    1.  هر گونه مکالمه ای [**حضوری**]{.ul} دو نفره که در آن [**حداقل دو سه کلمه**]{.ul} با هم صحبت کرده اید (مثلا سلام و احوالپرسی با همسایه) 

    2.  هرگونه [**تماس فیزیکی**]{.ul} پوستی (برای مثال دست دادن، بغل کردن، بوسیدن و یا ورزشهایی که در آنها تماس پوستی صورت میگیرد)
    :::

-   توجه داشته باشید هر روزی را که انتخاب کردید تا تماسهای آن روز را در سامانه ثبت کنید، شروع روز را [**ساعت 5 صبح**]{.ul} و پایان روز را ساعت [**5 صبح فردای همان روز**]{.ul} منظور کنید و تمامی تماسهایی که در این فاصله زمانی داشته اید را ثبت کنید. به عنوان مثال اگر فردی بخواهد تماسهای خود در تاریخ 17 فروردین را ثبت کند باید اطلاعات تمام تماسهای خود را که با افراد مختلف از ساعت 5 صبح 17 فروردین تا 5 صبح 18 فروردین (یعنی 24 ساعت) داشته است را در سامانه وارد کند.

-   [شما می بایست **تمام افرادی را که در طی 24 ساعت با آنها تماس داشته اید**]{.ul} صرف نظر از اینکه آن تماسها طولانی است یا کوتاه و اینکه آن افراد را می شناسید یا نه در صفحه اطلاعات تماس با زدن دکمه "افزودن" وارد کنید.

-   بعد از انتخاب عضو خانواده (که در شکل قبل "خودم" را انتخاب کردیم)، در قسمت پایین همان پنجره فرم دیگری (مانند شکل زیر) وجود دارد که می توانید اطلاعات فردی که این عضو از خانواده شما با وی تماس داشته است را وارد کنید. به عنوان مثال فردی قصد دارد تماس خود با دخترش که در خانه رخ داده است را برای تاریخ 17 فروردین ثبت کند. همانطور که در فرم تکمیل شده زیر مشاهده می فرمایید از آنجا که او سن دقیق دختر خود را میدانید، سن دقیق 7 سال را وارد کرده است. اگر شما با فردی تماس داشتید که سن دقیق وی را نمیدانستید می توانید یک محدوده سنی برای وی حدس بزنید (به عنوان مثال بین 40-45) و حد بالا و حد پایین را وارد کنید. فرد مورد مثال ما چون با دختر خود بازی می کند یا او را لمس میکند یا می بوسد پس تماس پوستی با وی رخ داده است. نسبت دخترش با وی از آنجا که پدرش می باشد "**فرزند**" انتخاب شده است. از آنجا که نه او و نه دخترش در خانه از ماسک استفاده نکرده اند پس جواب به سوال استفاده از ماسک، "**خیر**" انتخاب شده است. در این تماس فاصله فیزیکی "**کمتر از یک متر**" بوده است چون او با دخترش بازی می کند و تماس فیزیکی نزدیکی با او داشته است. از آنجا که وی هر روز با دخترش در منزل تماس دارد، پس تماس او با دخترش"**هر روز یا تقریبا هر روز**" در "**خانه**" رخ می دهد و مجموع مدت زمان تماسهای این فرد با دخترش"**بیشتر از 4 ساعت**" می باشد:

-   بعد از اینکه فرم را تکمیل نمودید، با کلیک کردن بر دکمه "**افزودن تماس**" اطلاعات تماس با فرد مورد نظر به جدول اطلاعات تماس شما اضافه خواهد شد. برای اطمینان از ذخیره شدن این تماس بر روی دکمه "**ذخیره**" کلیک کنید. بدین ترتیب شما می توانید به همین صورت تمامی تماسهایی که در تاریخ مورد نظرتان رخ داده است را برای خود و یا سایر اعضای خانواده ثبت کنید. مثلا ممکن است شما در طی 24 ساعت با 10 نفر تماس داشته باشید پس باید تمام این 10 تماس را برای خود ثبت کنید. اگر می خواهید اطلاعات تماس اعضای خانواده خود را نیز ثبت کنید، ابتدا عضو خانواده را در قسمت بالایی فرم انتخاب کنید و سپس بعد از پرسیدن تماسها از وی، تمام تماس های وی را در سامانه ثبت کنید.

-   در صورتی که نیاز به اصلاح هر تماس و یا حذف آن داشتید می توانید ابتدا تماس مورد نظر را از جدول تماسهای خود انتخاب کنید (بر روی ردیف تماس کلیک کنید) و سپس به کمک دکمه های "**ویرایش**" و "**حذف**"؛ تماس مورد نظر را ویرایش یا حذف کنید.

-   پس به طور خلاصه شما باید جواب سوالات زیر را در مورد تمامی افرادی که با آنها در طول یک شبانه روز تماس داشته اید به خاطر بیاورید و آنها را در سامانه ثبت کنید.

    ::: {dir="rtl" style="color: green"}
    -   **سن فردی که با وی تماس داشته اید؟**
    -   **جنسیت فردی که با وی تماس داشته اید؟**
    -   **چه مدت زمانی در طول روز مورد نظر با آن فرد در تماس بوده اید؟**
    -   **در چه مکانهایی تماس با آن فرد رخ داده است (ممکن است چند مکان را انتخاب کنید)؟**
    -   **به طور کلی هر چند وقت با آن فرد در تماس هستید؟**
    -   **آیا تماس پوستی با آن فرد وجود داشته است؟**
    :::

-   اگر در طی روز چندین بار با یک فرد تماس دارید، اطلاعات آن فرد را [**فقط یک بار**]{.ul} در [**یک ردیف**]{.ul} وارد کنید اما در قسمت مدت زمان تماس، مجموع زمانی را که با آن فرد در تماس بوده اید ثبت کنید. پس دقت کنید هر فرد را [**فقط یکبار**]{.ul} ثبت کنید. مثلا در مثال بالا فرد مورد نظر ما با دخترش در خانه چندین بار تماس دارد، پس به جای اینکه تماسهای خود با دخترش را در طی 24 ساعت چندین بار وارد کند، فقط زمان آن را بیشتر منظور میکند. پس باید [**کل مدت زمانی**]{.ul} را که [**در طول 24 ساعت**]{.ul} با فرد [**در تماس بوده اید**]{.ul} را ثبت کنید. به عنوان مثال شما 10 دقیقه در فروشگاه با یکی از دوستان خود صحبت کرده اید و با همین دوستتان در محل کار نیز 2 ساعت گفتگو کرده اید پس باید تماس مربوط به این فرد فقط یکبار ثبت شود اما مجموع زمان تماس با او در نظر گرفته و وارد شود که مجموع زمان برای این فرد بین 1 تا 4 ساعت می باشد. بعلاوه مکانهای تماس با این فرد نیز "محل کار" و "سایر" خواهد بود.

-   پس از درج تمامی تماسها برای خود یا اعضای خانواده، پیشنهاد می کنیم لطفا یکبار دیگر [**تمامی تماسهای**]{.ul} خود در تاریخ مورد نظر را به خاطر بیاورید و در صورتی که [**تماسی از قلم افتاده**]{.ul} است در سامانه ثبت کنید.

-   دقت کنید ترتیب ثبت تماسها با افراد در سامانه مهم نیست. ساده ترین کار این است که کل فعالیتهای روز مورد نظر خود را به خاطر بیاورید یا از اعضای خانواده خود بخواهید به خاطر بیاورند و اطلاعات افرادی که با آنها در تماس بوده اید را در سامانه وارد کنید.

**با تشکر از زمانی که برای مطالعه این راهنما اختصاص دادید.**

</font>
:::

```{=html}
<style>
  @font-face {
    font-family: "Vazir";
    src: url("./fonts/Vazir.eot");
    src: url("./fonts/Vazir.woff") format("woff"),
    url("./fonts/Vazir.otf") format("opentype"),
    url("./fonts/Vazir.svg") format("svg");
  }
body { 
  font-family: "Vazir";
  text-align: justify;
}
</style>
```
